SCOREBOARD_SCALING = 0.5
STD_SCOREBOARD_WIDTH = 870
STD_SCOREBOARD_HEIGHT = 352
SCOREBOARD_LEFT_X_OFFSET = 285
SCOREBOARD_Y_OFFSET = 174
SCOREBOARD_BORDER_WIDTH = 8
SCOREBOARD_INNER_LEFT_X_OFFSET = 10
SCOREBOARD_INNER_RIGHT_X_OFFSET = 437
SCOREBOARD_INNER_Y_BOT_OFFSET = 287
SCOREBOARD_INNER_TILE_WIDTH = 425
SCOREBOARD_INNER_TILE_HEIGHT = 57
SCOREBOARD_TOP_TILE_Y_OFFSET = 10
SCOREBOARD_ITEM_BORDER_WIDTH = 10
SCOREBOARD_INNER_BORDER_WIDTH = 3
SCOREBOARD_HEAD_Y_OFFSET = 44
SCOREBOARD_HEAD_LEFT_X_OFFSET = 27

CHAMP_CIRCLE = 34
CHAMP_SMALL_CIRCLE = 17
SMALL_CIRCLE_X_OFFSET = 5
SMALL_CIRCLE_Y_OFFSET = 6
CHAMP_IMG_BLACK_BORDER_WIDTH = 4
CHAMP_MIN_SIZE = 20
CHAMP_MAX_SIZE = 50

ITEM_MIN_SIZE = 15
ITEM_MAX_SIZE = 40



SPELL_MIN_SIZE = 15
SPELL_MAX_SIZE = 40


# different resolutions

# 1440x900
class Res_1440_900:

    CHAMP_LEFT_X_OFFSET = 335
    CHAMP_RIGHT_X_OFFSET = 813
    CHAMP_Y_OFFSET = 275
    CHAMP_Y_DIFF = 64
    CHAMP_SIZE = 23

    ITEM_LEFT_X_OFFSET = 516
    ITEM_RIGHT_X_OFFSET = 992
    ITEM_Y_DIFF = 64
    ITEM_Y_OFFSET = 276
    ITEM_X_DIFF = 28
    ITEM_SIZE = 24
    ITEM_INNER_OFFSET = 2

    SPELL_LEFT_X_OFFSET = 276
    SPELL_RIGHT_X_OFFSET = 754
    SPELL_Y_DIFF = 41
    SPELL_Y_DIFF_LARGE = 64
    SPELL_Y_OFFSET = 267
    SPELL_SIZE = 22

    SELF_INDICATOR_LEFT_X_OFFSET = 247
    SELF_INDICATOR_RIGHT_X_OFFSET = 723
    SELF_INDICATOR_Y_DIFF = 64
    SELF_INDICATOR_Y_OFFSET = 300
    SELF_INDICATOR_SIZE = 15

# 1600x900
class Res_1600_900:

    CHAMP_LEFT_X_OFFSET = 413
    CHAMP_RIGHT_X_OFFSET = 892
    CHAMP_Y_OFFSET = 275
    CHAMP_Y_DIFF = 64
    CHAMP_SIZE = 23

    ITEM_LEFT_X_OFFSET = 596
    ITEM_RIGHT_X_OFFSET = 1072
    ITEM_Y_DIFF = 64
    ITEM_Y_OFFSET = 276
    ITEM_X_DIFF = 28
    ITEM_SIZE = 24
    ITEM_INNER_OFFSET = 2

    SPELL_LEFT_X_OFFSET = 356
    SPELL_RIGHT_X_OFFSET = 834
    SPELL_Y_DIFF = 41
    SPELL_Y_DIFF_LARGE = 64
    SPELL_Y_OFFSET = 267
    SPELL_SIZE = 22

    SELF_INDICATOR_LEFT_X_OFFSET = 327
    SELF_INDICATOR_RIGHT_X_OFFSET = 802
    SELF_INDICATOR_Y_DIFF = 64
    SELF_INDICATOR_Y_OFFSET = 300
    SELF_INDICATOR_SIZE = 15


class Res_1920_1080:

    CHAMP_LEFT_X_OFFSET = 497
    CHAMP_RIGHT_X_OFFSET = 1071
    CHAMP_Y_OFFSET = 331
    CHAMP_Y_DIFF = 76
    CHAMP_SIZE = 28

    ITEM_LEFT_X_OFFSET = 715
    ITEM_RIGHT_X_OFFSET = 1286
    ITEM_Y_DIFF = 76
    ITEM_Y_OFFSET = 332
    ITEM_X_DIFF = 34
    ITEM_SIZE = 29
    ITEM_INNER_OFFSET = 2

    SPELL_LEFT_X_OFFSET = 356
    SPELL_RIGHT_X_OFFSET = 834
    SPELL_Y_DIFF = 41
    SPELL_Y_DIFF_LARGE = 64
    SPELL_Y_OFFSET = 267
    SPELL_SIZE = 22

    SELF_INDICATOR_LEFT_X_OFFSET = 392
    SELF_INDICATOR_RIGHT_X_OFFSET = 963
    SELF_INDICATOR_Y_DIFF = 76
    SELF_INDICATOR_Y_OFFSET = 360
    SELF_INDICATOR_SIZE = 18

