
NUM_SPELLS = 9
NUM_CHAMPS = 144
NUM_ITEMS = 203
NUM_SELF = 1

CHAMPS_PER_TEAM = 5
MAX_ITEMS_PER_CHAMP = 6
CHAMPS_PER_GAME = 10
SPELLS_PER_CHAMP = 2
SPELLS_PER_GAME = SPELLS_PER_CHAMP * CHAMPS_PER_GAME
NUM_FEATURES = CHAMPS_PER_GAME + CHAMPS_PER_GAME * SPELLS_PER_CHAMP + CHAMPS_PER_GAME * MAX_ITEMS_PER_CHAMP

